POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjMwNTQ5MTYsInVzZXJJRCI6MX0.7_qXEUBRRMN8bO11tTLggeTyc8bHVxIg_-ic5n4lNd8

{
    "name": "test eventt 45",
    "description": "another test event",
    "location": "a test location",
    "dateTime": "2025-01-01T13:30:00.000Z"
}