DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYzMDM5NzQwLCJ1c2VySUQiOjF9.2V9YdfTL_KGsHAOUdQi8iC-OmOW3MaGcfWQyEJsoEiE